// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: api/admin/v1/admin.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RaftAddr      string                 `protobuf:"bytes,2,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"` // the joining node's raft transport address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeRequest) Reset() {
	*x = AddNodeRequest{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeRequest) ProtoMessage() {}

func (x *AddNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeRequest.ProtoReflect.Descriptor instead.
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AddNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddNodeRequest) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

type AddNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *Cluster               `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"` // the resulting configuration, for immediate confirmation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeResponse) Reset() {
	*x = AddNodeResponse{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeResponse) ProtoMessage() {}

func (x *AddNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeResponse.ProtoReflect.Descriptor instead.
func (*AddNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AddNodeResponse) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type RemoveNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeRequest) Reset() {
	*x = RemoveNodeRequest{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeRequest) ProtoMessage() {}

func (x *RemoveNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *Cluster               `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeResponse) Reset() {
	*x = RemoveNodeResponse{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeResponse) ProtoMessage() {}

func (x *RemoveNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeResponse.ProtoReflect.Descriptor instead.
func (*RemoveNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveNodeResponse) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *Cluster               `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListNodesResponse) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type Cluster struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Nodes          []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	LeaderId       string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderRaftAddr string                 `protobuf:"bytes,3,opt,name=leader_raft_addr,json=leaderRaftAddr,proto3" json:"leader_raft_addr,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *Cluster) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Cluster) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *Cluster) GetLeaderRaftAddr() string {
	if x != nil {
		return x.LeaderRaftAddr
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RaftAddr      string                 `protobuf:"bytes,2,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	IsVoter       bool                   `protobuf:"varint,3,opt,name=is_voter,json=isVoter,proto3" json:"is_voter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_api_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

func (x *Node) GetIsVoter() bool {
	if x != nil {
		return x.IsVoter
	}
	return false
}

var File_api_admin_v1_admin_proto protoreflect.FileDescriptor

const file_api_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x18api/admin/v1/admin.proto\x12\ruddp.admin.v1\"=\n" +
	"\x0eAddNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\traft_addr\x18\x02 \x01(\tR\braftAddr\"C\n" +
	"\x0fAddNodeResponse\x120\n" +
	"\acluster\x18\x01 \x01(\v2\x16.uddp.admin.v1.ClusterR\acluster\"#\n" +
	"\x11RemoveNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x12RemoveNodeResponse\x120\n" +
	"\acluster\x18\x01 \x01(\v2\x16.uddp.admin.v1.ClusterR\acluster\"\x12\n" +
	"\x10ListNodesRequest\"E\n" +
	"\x11ListNodesResponse\x120\n" +
	"\acluster\x18\x01 \x01(\v2\x16.uddp.admin.v1.ClusterR\acluster\"{\n" +
	"\aCluster\x12)\n" +
	"\x05nodes\x18\x01 \x03(\v2\x13.uddp.admin.v1.NodeR\x05nodes\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12(\n" +
	"\x10leader_raft_addr\x18\x03 \x01(\tR\x0eleaderRaftAddr\"N\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\traft_addr\x18\x02 \x01(\tR\braftAddr\x12\x19\n" +
	"\bis_voter\x18\x03 \x01(\bR\aisVoter2\xfb\x01\n" +
	"\fAdminService\x12H\n" +
	"\aAddNode\x12\x1d.uddp.admin.v1.AddNodeRequest\x1a\x1e.uddp.admin.v1.AddNodeResponse\x12Q\n" +
	"\n" +
	"RemoveNode\x12 .uddp.admin.v1.RemoveNodeRequest\x1a!.uddp.admin.v1.RemoveNodeResponse\x12N\n" +
	"\tListNodes\x12\x1f.uddp.admin.v1.ListNodesRequest\x1a .uddp.admin.v1.ListNodesResponseB1Z/github.com/marknelson/uddp/api/admin/v1;adminv1b\x06proto3"

var (
	file_api_admin_v1_admin_proto_rawDescOnce sync.Once
	file_api_admin_v1_admin_proto_rawDescData []byte
)

func file_api_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_api_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_api_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_admin_v1_admin_proto_rawDesc), len(file_api_admin_v1_admin_proto_rawDesc)))
	})
	return file_api_admin_v1_admin_proto_rawDescData
}

var file_api_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_admin_v1_admin_proto_goTypes = []any{
	(*AddNodeRequest)(nil),     // 0: uddp.admin.v1.AddNodeRequest
	(*AddNodeResponse)(nil),    // 1: uddp.admin.v1.AddNodeResponse
	(*RemoveNodeRequest)(nil),  // 2: uddp.admin.v1.RemoveNodeRequest
	(*RemoveNodeResponse)(nil), // 3: uddp.admin.v1.RemoveNodeResponse
	(*ListNodesRequest)(nil),   // 4: uddp.admin.v1.ListNodesRequest
	(*ListNodesResponse)(nil),  // 5: uddp.admin.v1.ListNodesResponse
	(*Cluster)(nil),            // 6: uddp.admin.v1.Cluster
	(*Node)(nil),               // 7: uddp.admin.v1.Node
}
var file_api_admin_v1_admin_proto_depIdxs = []int32{
	6, // 0: uddp.admin.v1.AddNodeResponse.cluster:type_name -> uddp.admin.v1.Cluster
	6, // 1: uddp.admin.v1.RemoveNodeResponse.cluster:type_name -> uddp.admin.v1.Cluster
	6, // 2: uddp.admin.v1.ListNodesResponse.cluster:type_name -> uddp.admin.v1.Cluster
	7, // 3: uddp.admin.v1.Cluster.nodes:type_name -> uddp.admin.v1.Node
	0, // 4: uddp.admin.v1.AdminService.AddNode:input_type -> uddp.admin.v1.AddNodeRequest
	2, // 5: uddp.admin.v1.AdminService.RemoveNode:input_type -> uddp.admin.v1.RemoveNodeRequest
	4, // 6: uddp.admin.v1.AdminService.ListNodes:input_type -> uddp.admin.v1.ListNodesRequest
	1, // 7: uddp.admin.v1.AdminService.AddNode:output_type -> uddp.admin.v1.AddNodeResponse
	3, // 8: uddp.admin.v1.AdminService.RemoveNode:output_type -> uddp.admin.v1.RemoveNodeResponse
	5, // 9: uddp.admin.v1.AdminService.ListNodes:output_type -> uddp.admin.v1.ListNodesResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_admin_v1_admin_proto_init() }
func file_api_admin_v1_admin_proto_init() {
	if File_api_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_admin_v1_admin_proto_rawDesc), len(file_api_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_api_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_api_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_api_admin_v1_admin_proto = out.File
	file_api_admin_v1_admin_proto_goTypes = nil
	file_api_admin_v1_admin_proto_depIdxs = nil
}
