// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: api/native/v1/state.proto

package nativev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED   ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID       ErrorCode = 1
	ErrorCode_ERROR_CODE_UNAUTHORIZED  ErrorCode = 2
	ErrorCode_ERROR_CODE_CONFLICT      ErrorCode = 3
	ErrorCode_ERROR_CODE_THROTTLED     ErrorCode = 4
	ErrorCode_ERROR_CODE_UNAVAILABLE   ErrorCode = 5
	ErrorCode_ERROR_CODE_DEADLINE      ErrorCode = 6
	ErrorCode_ERROR_CODE_UNSUPPORTED   ErrorCode = 7
	ErrorCode_ERROR_CODE_INDETERMINATE ErrorCode = 8
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_INVALID",
		2: "ERROR_CODE_UNAUTHORIZED",
		3: "ERROR_CODE_CONFLICT",
		4: "ERROR_CODE_THROTTLED",
		5: "ERROR_CODE_UNAVAILABLE",
		6: "ERROR_CODE_DEADLINE",
		7: "ERROR_CODE_UNSUPPORTED",
		8: "ERROR_CODE_INDETERMINATE",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":   0,
		"ERROR_CODE_INVALID":       1,
		"ERROR_CODE_UNAUTHORIZED":  2,
		"ERROR_CODE_CONFLICT":      3,
		"ERROR_CODE_THROTTLED":     4,
		"ERROR_CODE_UNAVAILABLE":   5,
		"ERROR_CODE_DEADLINE":      6,
		"ERROR_CODE_UNSUPPORTED":   7,
		"ERROR_CODE_INDETERMINATE": 8,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_native_v1_state_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_native_v1_state_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_native_v1_state_proto_rawDescGZIP(), []int{0}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_native_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_native_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_native_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_native_v1_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_native_v1_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_native_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type PutRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId    string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	Key            []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value          []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds     int64                  `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // 0 = no expiry
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_api_native_v1_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_native_v1_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_api_native_v1_state_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *PutRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type DeleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId    string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	Key            []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_native_v1_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_native_v1_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_native_v1_state_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeleteRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CompareAndSetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId     string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	Key             []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value           []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ExpectedVersion uint64                 `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"` // 0 = key must not exist
	TtlSeconds      int64                  `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompareAndSetRequest) Reset() {
	*x = CompareAndSetRequest{}
	mi := &file_api_native_v1_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareAndSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareAndSetRequest) ProtoMessage() {}

func (x *CompareAndSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_native_v1_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareAndSetRequest.ProtoReflect.Descriptor instead.
func (*CompareAndSetRequest) Descriptor() ([]byte, []int) {
	return file_api_native_v1_state_proto_rawDescGZIP(), []int{4}
}

func (x *CompareAndSetRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *CompareAndSetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CompareAndSetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CompareAndSetRequest) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *CompareAndSetRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *CompareAndSetRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type MutationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId       string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	PartitionId       uint32                 `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Epoch             uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	CommitPosition    uint64                 `protobuf:"varint,4,opt,name=commit_position,json=commitPosition,proto3" json:"commit_position,omitempty"`
	DurabilityProfile string                 `protobuf:"bytes,5,opt,name=durability_profile,json=durabilityProfile,proto3" json:"durability_profile,omitempty"`
	Deduplicated      bool                   `protobuf:"varint,6,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"`
	Version           uint64                 `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MutationResponse) Reset() {
	*x = MutationResponse{}
	mi := &file_api_native_v1_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationResponse) ProtoMessage() {}

func (x *MutationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_native_v1_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationResponse.ProtoReflect.Descriptor instead.
func (*MutationResponse) Descriptor() ([]byte, []int) {
	return file_api_native_v1_state_proto_rawDescGZIP(), []int{5}
}

func (x *MutationResponse) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *MutationResponse) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *MutationResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *MutationResponse) GetCommitPosition() uint64 {
	if x != nil {
		return x.CommitPosition
	}
	return 0
}

func (x *MutationResponse) GetDurabilityProfile() string {
	if x != nil {
		return x.DurabilityProfile
	}
	return ""
}

func (x *MutationResponse) GetDeduplicated() bool {
	if x != nil {
		return x.Deduplicated
	}
	return false
}

func (x *MutationResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_api_native_v1_state_proto protoreflect.FileDescriptor

const file_api_native_v1_state_proto_rawDesc = "" +
	"\n" +
	"\x19api/native/v1/state.proto\x12\x0euddp.native.v1\"A\n" +
	"\n" +
	"GetRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"S\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"\xa1\x01\n" +
	"\n" +
	"PutRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x03R\n" +
	"ttlSeconds\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"m\n" +
	"\rDeleteRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"\xd6\x01\n" +
	"\x14CompareAndSetRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12)\n" +
	"\x10expected_version\x18\x04 \x01(\x04R\x0fexpectedVersion\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x03R\n" +
	"ttlSeconds\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\"\x84\x02\n" +
	"\x10MutationResponse\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\rR\vpartitionId\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\x12'\n" +
	"\x0fcommit_position\x18\x04 \x01(\x04R\x0ecommitPosition\x12-\n" +
	"\x12durability_profile\x18\x05 \x01(\tR\x11durabilityProfile\x12\"\n" +
	"\fdeduplicated\x18\x06 \x01(\bR\fdeduplicated\x12\x18\n" +
	"\aversion\x18\a \x01(\x04R\aversion*\xfe\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ERROR_CODE_INVALID\x10\x01\x12\x1b\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\x02\x12\x17\n" +
	"\x13ERROR_CODE_CONFLICT\x10\x03\x12\x18\n" +
	"\x14ERROR_CODE_THROTTLED\x10\x04\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\x05\x12\x17\n" +
	"\x13ERROR_CODE_DEADLINE\x10\x06\x12\x1a\n" +
	"\x16ERROR_CODE_UNSUPPORTED\x10\a\x12\x1c\n" +
	"\x18ERROR_CODE_INDETERMINATE\x10\b2\xb7\x02\n" +
	"\fStateService\x12>\n" +
	"\x03Get\x12\x1a.uddp.native.v1.GetRequest\x1a\x1b.uddp.native.v1.GetResponse\x12C\n" +
	"\x03Put\x12\x1a.uddp.native.v1.PutRequest\x1a .uddp.native.v1.MutationResponse\x12I\n" +
	"\x06Delete\x12\x1d.uddp.native.v1.DeleteRequest\x1a .uddp.native.v1.MutationResponse\x12W\n" +
	"\rCompareAndSet\x12$.uddp.native.v1.CompareAndSetRequest\x1a .uddp.native.v1.MutationResponseB3Z1github.com/marknelson/uddp/api/native/v1;nativev1b\x06proto3"

var (
	file_api_native_v1_state_proto_rawDescOnce sync.Once
	file_api_native_v1_state_proto_rawDescData []byte
)

func file_api_native_v1_state_proto_rawDescGZIP() []byte {
	file_api_native_v1_state_proto_rawDescOnce.Do(func() {
		file_api_native_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_native_v1_state_proto_rawDesc), len(file_api_native_v1_state_proto_rawDesc)))
	})
	return file_api_native_v1_state_proto_rawDescData
}

var file_api_native_v1_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_native_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_native_v1_state_proto_goTypes = []any{
	(ErrorCode)(0),               // 0: uddp.native.v1.ErrorCode
	(*GetRequest)(nil),           // 1: uddp.native.v1.GetRequest
	(*GetResponse)(nil),          // 2: uddp.native.v1.GetResponse
	(*PutRequest)(nil),           // 3: uddp.native.v1.PutRequest
	(*DeleteRequest)(nil),        // 4: uddp.native.v1.DeleteRequest
	(*CompareAndSetRequest)(nil), // 5: uddp.native.v1.CompareAndSetRequest
	(*MutationResponse)(nil),     // 6: uddp.native.v1.MutationResponse
}
var file_api_native_v1_state_proto_depIdxs = []int32{
	1, // 0: uddp.native.v1.StateService.Get:input_type -> uddp.native.v1.GetRequest
	3, // 1: uddp.native.v1.StateService.Put:input_type -> uddp.native.v1.PutRequest
	4, // 2: uddp.native.v1.StateService.Delete:input_type -> uddp.native.v1.DeleteRequest
	5, // 3: uddp.native.v1.StateService.CompareAndSet:input_type -> uddp.native.v1.CompareAndSetRequest
	2, // 4: uddp.native.v1.StateService.Get:output_type -> uddp.native.v1.GetResponse
	6, // 5: uddp.native.v1.StateService.Put:output_type -> uddp.native.v1.MutationResponse
	6, // 6: uddp.native.v1.StateService.Delete:output_type -> uddp.native.v1.MutationResponse
	6, // 7: uddp.native.v1.StateService.CompareAndSet:output_type -> uddp.native.v1.MutationResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_native_v1_state_proto_init() }
func file_api_native_v1_state_proto_init() {
	if File_api_native_v1_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_native_v1_state_proto_rawDesc), len(file_api_native_v1_state_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_native_v1_state_proto_goTypes,
		DependencyIndexes: file_api_native_v1_state_proto_depIdxs,
		EnumInfos:         file_api_native_v1_state_proto_enumTypes,
		MessageInfos:      file_api_native_v1_state_proto_msgTypes,
	}.Build()
	File_api_native_v1_state_proto = out.File
	file_api_native_v1_state_proto_goTypes = nil
	file_api_native_v1_state_proto_depIdxs = nil
}
