// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: api/native/v1/stream.proto

package nativev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeKind int32

const (
	ChangeKind_CHANGE_KIND_UNSPECIFIED ChangeKind = 0
	ChangeKind_CHANGE_KIND_PUT         ChangeKind = 1
	ChangeKind_CHANGE_KIND_DELETE      ChangeKind = 2
)

// Enum value maps for ChangeKind.
var (
	ChangeKind_name = map[int32]string{
		0: "CHANGE_KIND_UNSPECIFIED",
		1: "CHANGE_KIND_PUT",
		2: "CHANGE_KIND_DELETE",
	}
	ChangeKind_value = map[string]int32{
		"CHANGE_KIND_UNSPECIFIED": 0,
		"CHANGE_KIND_PUT":         1,
		"CHANGE_KIND_DELETE":      2,
	}
)

func (x ChangeKind) Enum() *ChangeKind {
	p := new(ChangeKind)
	*p = x
	return p
}

func (x ChangeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_native_v1_stream_proto_enumTypes[0].Descriptor()
}

func (ChangeKind) Type() protoreflect.EnumType {
	return &file_api_native_v1_stream_proto_enumTypes[0]
}

func (x ChangeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeKind.Descriptor instead.
func (ChangeKind) EnumDescriptor() ([]byte, []int) {
	return file_api_native_v1_stream_proto_rawDescGZIP(), []int{0}
}

type ChangeRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Kind          ChangeKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=uddp.native.v1.ChangeKind" json:"kind,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"` // empty for CHANGE_KIND_DELETE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRecord) Reset() {
	*x = ChangeRecord{}
	mi := &file_api_native_v1_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRecord) ProtoMessage() {}

func (x *ChangeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_native_v1_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRecord.ProtoReflect.Descriptor instead.
func (*ChangeRecord) Descriptor() ([]byte, []int) {
	return file_api_native_v1_stream_proto_rawDescGZIP(), []int{0}
}

func (x *ChangeRecord) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ChangeRecord) GetKind() ChangeKind {
	if x != nil {
		return x.Kind
	}
	return ChangeKind_CHANGE_KIND_UNSPECIFIED
}

func (x *ChangeRecord) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ChangeRecord) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	FromOffset    uint64                 `protobuf:"varint,2,opt,name=from_offset,json=fromOffset,proto3" json:"from_offset,omitempty"` // inclusive; 0 is invalid (offsets start at 1)
	MaxRecords    int32                  `protobuf:"varint,3,opt,name=max_records,json=maxRecords,proto3" json:"max_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_api_native_v1_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_native_v1_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_api_native_v1_stream_proto_rawDescGZIP(), []int{1}
}

func (x *FetchRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *FetchRequest) GetFromOffset() uint64 {
	if x != nil {
		return x.FromOffset
	}
	return 0
}

func (x *FetchRequest) GetMaxRecords() int32 {
	if x != nil {
		return x.MaxRecords
	}
	return 0
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*ChangeRecord        `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	NextOffset    uint64                 `protobuf:"varint,2,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"` // offset to pass as from_offset on the next call
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_api_native_v1_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_native_v1_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_api_native_v1_stream_proto_rawDescGZIP(), []int{2}
}

func (x *FetchResponse) GetRecords() []*ChangeRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *FetchResponse) GetNextOffset() uint64 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

type CommitOffsetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	ConsumerGroup string                 `protobuf:"bytes,2,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOffsetRequest) Reset() {
	*x = CommitOffsetRequest{}
	mi := &file_api_native_v1_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOffsetRequest) ProtoMessage() {}

func (x *CommitOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_native_v1_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOffsetRequest.ProtoReflect.Descriptor instead.
func (*CommitOffsetRequest) Descriptor() ([]byte, []int) {
	return file_api_native_v1_stream_proto_rawDescGZIP(), []int{3}
}

func (x *CommitOffsetRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *CommitOffsetRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *CommitOffsetRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CommitOffsetResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommittedOffset uint64                 `protobuf:"varint,1,opt,name=committed_offset,json=committedOffset,proto3" json:"committed_offset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommitOffsetResponse) Reset() {
	*x = CommitOffsetResponse{}
	mi := &file_api_native_v1_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOffsetResponse) ProtoMessage() {}

func (x *CommitOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_native_v1_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOffsetResponse.ProtoReflect.Descriptor instead.
func (*CommitOffsetResponse) Descriptor() ([]byte, []int) {
	return file_api_native_v1_stream_proto_rawDescGZIP(), []int{4}
}

func (x *CommitOffsetResponse) GetCommittedOffset() uint64 {
	if x != nil {
		return x.CommittedOffset
	}
	return 0
}

type FetchOffsetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	ConsumerGroup string                 `protobuf:"bytes,2,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOffsetRequest) Reset() {
	*x = FetchOffsetRequest{}
	mi := &file_api_native_v1_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOffsetRequest) ProtoMessage() {}

func (x *FetchOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_native_v1_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOffsetRequest.ProtoReflect.Descriptor instead.
func (*FetchOffsetRequest) Descriptor() ([]byte, []int) {
	return file_api_native_v1_stream_proto_rawDescGZIP(), []int{5}
}

func (x *FetchOffsetRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *FetchOffsetRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

type FetchOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOffsetResponse) Reset() {
	*x = FetchOffsetResponse{}
	mi := &file_api_native_v1_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOffsetResponse) ProtoMessage() {}

func (x *FetchOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_native_v1_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOffsetResponse.ProtoReflect.Descriptor instead.
func (*FetchOffsetResponse) Descriptor() ([]byte, []int) {
	return file_api_native_v1_stream_proto_rawDescGZIP(), []int{6}
}

func (x *FetchOffsetResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FetchOffsetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_api_native_v1_stream_proto protoreflect.FileDescriptor

const file_api_native_v1_stream_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/native/v1/stream.proto\x12\x0euddp.native.v1\"~\n" +
	"\fChangeRecord\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12.\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1a.uddp.native.v1.ChangeKindR\x04kind\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\"s\n" +
	"\fFetchRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1f\n" +
	"\vfrom_offset\x18\x02 \x01(\x04R\n" +
	"fromOffset\x12\x1f\n" +
	"\vmax_records\x18\x03 \x01(\x05R\n" +
	"maxRecords\"h\n" +
	"\rFetchResponse\x126\n" +
	"\arecords\x18\x01 \x03(\v2\x1c.uddp.native.v1.ChangeRecordR\arecords\x12\x1f\n" +
	"\vnext_offset\x18\x02 \x01(\x04R\n" +
	"nextOffset\"w\n" +
	"\x13CommitOffsetRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12%\n" +
	"\x0econsumer_group\x18\x02 \x01(\tR\rconsumerGroup\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"A\n" +
	"\x14CommitOffsetResponse\x12)\n" +
	"\x10committed_offset\x18\x01 \x01(\x04R\x0fcommittedOffset\"^\n" +
	"\x12FetchOffsetRequest\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12%\n" +
	"\x0econsumer_group\x18\x02 \x01(\tR\rconsumerGroup\"C\n" +
	"\x13FetchOffsetResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found*V\n" +
	"\n" +
	"ChangeKind\x12\x1b\n" +
	"\x17CHANGE_KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCHANGE_KIND_PUT\x10\x01\x12\x16\n" +
	"\x12CHANGE_KIND_DELETE\x10\x022\x88\x02\n" +
	"\rStreamService\x12D\n" +
	"\x05Fetch\x12\x1c.uddp.native.v1.FetchRequest\x1a\x1d.uddp.native.v1.FetchResponse\x12Y\n" +
	"\fCommitOffset\x12#.uddp.native.v1.CommitOffsetRequest\x1a$.uddp.native.v1.CommitOffsetResponse\x12V\n" +
	"\vFetchOffset\x12\".uddp.native.v1.FetchOffsetRequest\x1a#.uddp.native.v1.FetchOffsetResponseB3Z1github.com/marknelson/uddp/api/native/v1;nativev1b\x06proto3"

var (
	file_api_native_v1_stream_proto_rawDescOnce sync.Once
	file_api_native_v1_stream_proto_rawDescData []byte
)

func file_api_native_v1_stream_proto_rawDescGZIP() []byte {
	file_api_native_v1_stream_proto_rawDescOnce.Do(func() {
		file_api_native_v1_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_native_v1_stream_proto_rawDesc), len(file_api_native_v1_stream_proto_rawDesc)))
	})
	return file_api_native_v1_stream_proto_rawDescData
}

var file_api_native_v1_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_native_v1_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_native_v1_stream_proto_goTypes = []any{
	(ChangeKind)(0),              // 0: uddp.native.v1.ChangeKind
	(*ChangeRecord)(nil),         // 1: uddp.native.v1.ChangeRecord
	(*FetchRequest)(nil),         // 2: uddp.native.v1.FetchRequest
	(*FetchResponse)(nil),        // 3: uddp.native.v1.FetchResponse
	(*CommitOffsetRequest)(nil),  // 4: uddp.native.v1.CommitOffsetRequest
	(*CommitOffsetResponse)(nil), // 5: uddp.native.v1.CommitOffsetResponse
	(*FetchOffsetRequest)(nil),   // 6: uddp.native.v1.FetchOffsetRequest
	(*FetchOffsetResponse)(nil),  // 7: uddp.native.v1.FetchOffsetResponse
}
var file_api_native_v1_stream_proto_depIdxs = []int32{
	0, // 0: uddp.native.v1.ChangeRecord.kind:type_name -> uddp.native.v1.ChangeKind
	1, // 1: uddp.native.v1.FetchResponse.records:type_name -> uddp.native.v1.ChangeRecord
	2, // 2: uddp.native.v1.StreamService.Fetch:input_type -> uddp.native.v1.FetchRequest
	4, // 3: uddp.native.v1.StreamService.CommitOffset:input_type -> uddp.native.v1.CommitOffsetRequest
	6, // 4: uddp.native.v1.StreamService.FetchOffset:input_type -> uddp.native.v1.FetchOffsetRequest
	3, // 5: uddp.native.v1.StreamService.Fetch:output_type -> uddp.native.v1.FetchResponse
	5, // 6: uddp.native.v1.StreamService.CommitOffset:output_type -> uddp.native.v1.CommitOffsetResponse
	7, // 7: uddp.native.v1.StreamService.FetchOffset:output_type -> uddp.native.v1.FetchOffsetResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_native_v1_stream_proto_init() }
func file_api_native_v1_stream_proto_init() {
	if File_api_native_v1_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_native_v1_stream_proto_rawDesc), len(file_api_native_v1_stream_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_native_v1_stream_proto_goTypes,
		DependencyIndexes: file_api_native_v1_stream_proto_depIdxs,
		EnumInfos:         file_api_native_v1_stream_proto_enumTypes,
		MessageInfos:      file_api_native_v1_stream_proto_msgTypes,
	}.Build()
	File_api_native_v1_stream_proto = out.File
	file_api_native_v1_stream_proto_goTypes = nil
	file_api_native_v1_stream_proto_depIdxs = nil
}
